# -*- coding: utf-8 -*-
"""Код для MVP-скелета iTSAR (Python + HTML)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h28hFgetVGHk88ZlzZtYDdY6vcx-Atqc
"""

# server.py
# Простейший веб-сервер на aiohttp для обслуживания Telegram Mini App

import os
from aiohttp import web
import logging

# --- КОНФИГУРАЦИЯ ---
# ВАЖНО: Вставьте сюда токен, который вы получили от BotFather
BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '8166250106:AAFplSP-kDulNCdw1D_tyLUxkZEnEfE_Nlc')
PORT = int(os.getenv('PORT', 8080))

logging.basicConfig(level=logging.INFO)

# --- ОБРАБОТЧИКИ ЗАПРОСОВ ---

# Этот обработчик будет отдавать нашу главную HTML-страницу
async def handle_index(request):
    """
    Отдает главный файл index.html, который и является нашим Mini App.
    """
    logging.info("Отдаем index.html")
    try:
        return web.FileResponse('./index.html')
    except Exception as e:
        logging.error(f"Ошибка при чтении index.html: {e}")
        return web.Response(text="Ошибка сервера: не найден index.html", status=500)

# --- ЗАПУСК ВЕБ-СЕРВЕРА ---

# Создаем приложение
app = web.Application()

# Добавляем маршруты (роуты)
app.router.add_get('/', handle_index)

# Функция для запуска
async def start_server():
    """
    Запускает веб-сервер.
    """
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, '0.0.0.0', PORT)
    await site.start()
    logging.info(f"Сервер iTSAR запущен на порту {PORT}")
    # В реальном приложении здесь будет бесконечный цикл
    # Для простоты прототипа мы просто ждем
    while True:
        await asyncio.sleep(3600) # Держим сервер живым

if __name__ == "__main__":
    # Установка зависимостей: pip install aiohttp
    import asyncio
    logging.info("Запуск сервера...")
    if BOT_TOKEN == 'YOUR_TELEGRAM_BOT_TOKEN':
        logging.warning("!!! ВНИМАНИЕ: Вы не указали токен бота. Пожалуйста, вставьте его в переменную BOT_TOKEN.")
    else:
        logging.info(f"Токен бота успешно загружен (первые 5 символов: {BOT_TOKEN[:5]}...).")

    try:
        asyncio.run(start_server())
    except KeyboardInterrupt:
        logging.info("Сервер остановлен.")
